// SPDX-License-Identifier: LGPL-3.0-or-later

package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

const rosalineModule = "github.com/SeraphinaDX/Rosaline"
const generatedMarker = "Code generated by Rosaline Studio. DO NOT EDIT."

type generationReport struct {
	Created []string
	Updated []string
	Kept    []string
}

type generatedField struct {
	Name string
	Type string
}

type generationContext struct {
	fieldsByID map[string]generatedField
	fields     []generatedField
}

func generateProject(project *designProject, directory string) (generationReport, error) {
	var report generationReport
	if err := project.validate(); err != nil {
		return report, err
	}
	if strings.TrimSpace(directory) == "" {
		return report, fmt.Errorf("choose a project folder first")
	}
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return report, fmt.Errorf("create project folder: %w", err)
	}

	context := makeGenerationContext(project)
	generated := map[string]string{
		"ui_generated.go":    generatedUI(project, context),
		"state_generated.go": generatedState(context),
	}
	for name, contents := range generated {
		formatted, err := format.Source([]byte(contents))
		if err != nil {
			return report, fmt.Errorf("format %s: %w", name, err)
		}
		path := filepath.Join(directory, name)
		existed, err := replaceGeneratedFile(path, formatted)
		if err != nil {
			return report, fmt.Errorf("write %s: %w", name, err)
		}
		if existed {
			report.Updated = append(report.Updated, name)
		} else {
			report.Created = append(report.Created, name)
		}
	}

	protected := map[string]string{
		"go.mod":      generatedGoMod(project),
		"main.go":     generatedMain(),
		"handlers.go": generatedHandlers(),
		"README.md":   generatedReadme(project),
	}
	for name, contents := range protected {
		path := filepath.Join(directory, name)
		if _, err := os.Stat(path); err == nil {
			report.Kept = append(report.Kept, name)
			continue
		} else if !os.IsNotExist(err) {
			return report, fmt.Errorf("inspect %s: %w", name, err)
		}
		if strings.HasSuffix(name, ".go") {
			formatted, err := format.Source([]byte(contents))
			if err != nil {
				return report, fmt.Errorf("format %s: %w", name, err)
			}
			contents = string(formatted)
		}
		if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
			return report, fmt.Errorf("write %s: %w", name, err)
		}
		report.Created = append(report.Created, name)
	}

	sort.Strings(report.Created)
	sort.Strings(report.Updated)
	sort.Strings(report.Kept)
	return report, nil
}

func replaceGeneratedFile(path string, contents []byte) (bool, error) {
	existing, err := os.ReadFile(path)
	if err == nil {
		if !strings.Contains(string(existing), generatedMarker) {
			return true, fmt.Errorf("refusing to replace an existing file without the Rosaline Studio generation marker")
		}
		return true, writeFileAtomically(path, contents, 0o644)
	}
	if !os.IsNotExist(err) {
		return false, err
	}
	return false, writeFileAtomically(path, contents, 0o644)
}

func writeFileAtomically(path string, contents []byte, permission os.FileMode) error {
	temporary, err := os.CreateTemp(filepath.Dir(path), ".rosaline-studio-*")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer func() {
		_ = temporary.Close()
		_ = os.Remove(temporaryPath)
	}()
	if err := temporary.Chmod(permission); err != nil {
		return err
	}
	if _, err := temporary.Write(contents); err != nil {
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryPath, path)
}

func makeGenerationContext(project *designProject) *generationContext {
	context := &generationContext{fieldsByID: make(map[string]generatedField)}
	used := make(map[string]int)
	var visit func(*designNode)
	visit = func(node *designNode) {
		if node == nil {
			return
		}
		fieldType := stateType(node.Kind)
		if fieldType != "" {
			base := exportedIdentifier(node.Name)
			if base == "" {
				base = exportedIdentifier(string(node.Kind))
			}
			used[base]++
			name := base
			if used[base] > 1 {
				name += strconv.Itoa(used[base])
			}
			field := generatedField{Name: name, Type: fieldType}
			context.fieldsByID[node.ID] = field
			context.fields = append(context.fields, field)
		}
		for _, child := range node.Children {
			visit(child)
		}
	}
	visit(project.Root)
	return context
}

func stateType(kind widgetKind) string {
	switch kind {
	case kindTextBox, kindTextArea, kindComboBox:
		return "string"
	case kindCheckBox:
		return "bool"
	case kindSlider, kindProgressBar:
		return "float64"
	default:
		return ""
	}
}

func exportedIdentifier(value string) string {
	words := strings.FieldsFunc(value, func(r rune) bool { return !unicode.IsLetter(r) && !unicode.IsDigit(r) })
	var builder strings.Builder
	for _, word := range words {
		if word == "" {
			continue
		}
		runes := []rune(word)
		runes[0] = unicode.ToUpper(runes[0])
		builder.WriteString(string(runes))
	}
	result := builder.String()
	if result == "" || unicode.IsDigit([]rune(result)[0]) {
		return "Value"
	}
	return result
}

func generatedUI(project *designProject, context *generationContext) string {
	return fmt.Sprintf(`// %s
package main

import rosaline %q

func runGeneratedApplication(app *Application) {
	rosaline.RunApp(rosaline.App{
		Title: %q,
		Width: %d,
		Height: %d,
		Padding: %d,
		Theme: studioTheme(),
		Content: buildUI(app),
	})
}

func buildUI(app *Application) rosaline.Widget {
	return %s
}

%s
`, generatedMarker, rosalineModule, project.Title, max(320, project.Width), max(240, project.Height), max(0, project.Padding), generateNode(project.Root, context, 1), generatedTheme(project.Theme))
}

func generatedState(context *generationContext) string {
	var fields strings.Builder
	for _, field := range context.fields {
		fmt.Fprintf(&fields, "\t%s %s\n", field.Name, field.Type)
	}
	return fmt.Sprintf(`// %s
package main

// UIState contains values bound to generated Rosaline controls.
type UIState struct {
%s}
`, generatedMarker, fields.String())
}

func generatedMain() string {
	return `package main

func main() {
	runGeneratedApplication(&Application{})
}
`
}

func generatedHandlers() string {
	return `package main

import (
	"fmt"

	rosaline "github.com/SeraphinaDX/Rosaline"
)

// Application contains your program's state and behavior. Rosaline Studio
// never overwrites this file.
type Application struct {
	State UIState
}

// Action receives the action name assigned in Rosaline Studio. Add cases as
// your application grows.
func (app *Application) Action(name string) {
	switch name {
	case "continue":
		rosaline.Message("Your application", "Continue action received.")
	default:
		fmt.Println("Rosaline action:", name)
	}
}
`
}

func generatedGoMod(project *designProject) string {
	return fmt.Sprintf("module %s\n\ngo 1.25.0\n\nrequire %s v0.15.0\n", strings.TrimSpace(project.Module), rosalineModule)
}

func generatedReadme(project *designProject) string {
	return fmt.Sprintf(`# %s

This application was visually designed with Rosaline Studio.

Run it with:

~~~bash
CGO_ENABLED=0 go run .
~~~

Edit application behavior in handlers.go. Rosaline Studio may regenerate
ui_generated.go and state_generated.go, so do not edit those two files.
`, project.Title)
}

func generatedTheme(name string) string {
	switch name {
	case "Midnight":
		return `func studioTheme() rosaline.Theme {
	theme := rosaline.DefaultTheme
	theme.Background = rosaline.Hex("#140d1d")
	theme.Surface = rosaline.Hex("#24152e")
	theme.Primary = rosaline.Hex("#ff79b7")
	theme.Text = rosaline.Hex("#fff0fa")
	theme.Muted = rosaline.Hex("#c39ab4")
	theme.Border = rosaline.Hex("#73445f")
	return theme
}`
	case "Lavender":
		return `func studioTheme() rosaline.Theme {
	theme := rosaline.DefaultTheme
	theme.Background = rosaline.Hex("#f7f1ff")
	theme.Surface = rosaline.Hex("#ffffff")
	theme.Primary = rosaline.Hex("#8554bd")
	theme.Text = rosaline.Hex("#2d2038")
	theme.Muted = rosaline.Hex("#74627f")
	theme.Border = rosaline.Hex("#d7c3e9")
	return theme
}`
	default:
		return `func studioTheme() rosaline.Theme { return rosaline.DefaultTheme }`
	}
}

func generateNode(node *designNode, context *generationContext, depth int) string {
	if node == nil {
		return "rosaline.Spacer(0, 0)"
	}
	indent := strings.Repeat("\t", depth)
	childIndent := strings.Repeat("\t", depth+1)
	children := func() string {
		if len(node.Children) == 0 {
			return ""
		}
		parts := make([]string, 0, len(node.Children))
		for _, child := range node.Children {
			parts = append(parts, childIndent+generateNode(child, context, depth+1))
		}
		return "\n" + strings.Join(parts, ",\n") + ",\n" + indent
	}
	oneChild := func() string {
		if len(node.Children) == 0 {
			return "rosaline.Spacer(0, 0)"
		}
		return generateNode(node.Children[0], context, depth+1)
	}

	var expression string
	switch node.Kind {
	case kindColumn:
		expression = "rosaline.Column(" + children() + ")" + layoutModifiers(node)
	case kindRow:
		expression = "rosaline.Row(" + children() + ")" + layoutModifiers(node)
	case kindGrid:
		childList := children()
		if childList == "" {
			expression = fmt.Sprintf("rosaline.Grid(%d)", max(1, node.Columns))
		} else {
			expression = fmt.Sprintf("rosaline.Grid(%d,%s)", max(1, node.Columns), childList)
		}
		expression += layoutModifiers(node)
	case kindStack:
		expression = "rosaline.Stack(" + children() + ")"
		if node.Expand {
			expression += ".Expand()"
		}
	case kindCard:
		expression = fmt.Sprintf("rosaline.Card(%s).Padding(%d)", oneChild(), max(0, node.Padding))
		if node.Expand {
			expression += ".Expand()"
		}
	case kindScroll:
		expression = "rosaline.Scroll(" + oneChild() + ")"
		if node.Width > 0 && node.Height > 0 {
			expression += fmt.Sprintf(".Size(%d, %d)", node.Width, node.Height)
		}
		if node.Expand {
			expression += ".Expand()"
		}
	case kindLabel:
		expression = fmt.Sprintf("rosaline.Label(%q)", node.Text)
		if node.Bold {
			expression += ".Bold()"
		}
	case kindButton:
		action := strings.TrimSpace(node.Action)
		if action == "" {
			action = node.ID
		}
		expression = fmt.Sprintf("rosaline.Button(%q, func() { app.Action(%q) })", node.Text, action)
		if node.Primary {
			expression += ".Primary()"
		}
	case kindTextBox:
		field := context.fieldsByID[node.ID]
		expression = fmt.Sprintf("rosaline.TextBox(&app.State.%s)", field.Name)
		if node.Text != "" {
			expression += fmt.Sprintf(".Placeholder(%q)", node.Text)
		}
		if node.Password {
			expression += ".Password()"
		}
	case kindTextArea:
		field := context.fieldsByID[node.ID]
		expression = fmt.Sprintf("rosaline.TextArea(&app.State.%s)", field.Name)
		if node.Expand {
			expression += ".Expand()"
		}
	case kindCheckBox:
		field := context.fieldsByID[node.ID]
		expression = fmt.Sprintf("rosaline.CheckBox(%q, &app.State.%s)", node.Text, field.Name)
	case kindComboBox:
		field := context.fieldsByID[node.ID]
		options := make([]string, 0, len(node.Options))
		for _, option := range node.Options {
			options = append(options, strconv.Quote(option))
		}
		expression = fmt.Sprintf("rosaline.ComboBox(&app.State.%s", field.Name)
		if len(options) != 0 {
			expression += ", " + strings.Join(options, ", ")
		}
		expression += ")"
	case kindSlider:
		field := context.fieldsByID[node.ID]
		minimum, maximum := node.Minimum, node.Maximum
		if maximum <= minimum {
			maximum = minimum + 100
		}
		expression = fmt.Sprintf("rosaline.Slider(&app.State.%s, %s, %s)", field.Name, numberLiteral(minimum), numberLiteral(maximum))
		if node.Step > 0 {
			expression += fmt.Sprintf(".Step(%s)", numberLiteral(node.Step))
		}
		if node.Vertical {
			expression += ".Vertical()"
		}
	case kindProgressBar:
		field := context.fieldsByID[node.ID]
		expression = fmt.Sprintf("rosaline.ProgressBar(&app.State.%s)", field.Name)
		if node.Maximum > 0 && node.Maximum != 100 {
			expression += fmt.Sprintf(".Maximum(%s)", numberLiteral(node.Maximum))
		}
		if node.Vertical {
			expression += ".Vertical()"
		}
	case kindSpacer:
		expression = fmt.Sprintf("rosaline.Spacer(%d, %d)", max(0, node.Width), max(0, node.Height))
	default:
		expression = "rosaline.Label(\"Unknown widget\")"
	}

	if node.Kind != kindScroll && node.Kind != kindSpacer && node.Width > 0 && node.Height > 0 {
		expression = fmt.Sprintf("rosaline.Size(%s, %d, %d)", expression, node.Width, node.Height)
	}
	return expression
}

func layoutModifiers(node *designNode) string {
	result := fmt.Sprintf(".Gap(%d).Padding(%d)", max(0, node.Gap), max(0, node.Padding))
	if node.Expand {
		result += ".Expand()"
	}
	return result
}

func numberLiteral(value float64) string {
	return strconv.FormatFloat(value, 'f', -1, 64)
}
