// SPDX-License-Identifier: LGPL-3.0-or-later

package main

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

const rosalineModule = "github.com/SeraphinaDX/Rosaline"
const rosalineVersion = "v0.19.0"
const generatedMarker = "Code generated by Rosaline Studio. DO NOT EDIT."

type generationReport struct {
	Created []string
	Updated []string
	Kept    []string
}

type generatedField struct {
	Name string
	Type string
}

type generationContext struct {
	fieldsByID  map[string]generatedField
	fields      []generatedField
	widgetsByID map[string]generatedField
	widgets     []generatedField
}

func generatedApplicationDirectory(designPath string) string {
	directory := filepath.Dir(designPath)
	filename := filepath.Base(designPath)
	name := strings.TrimSuffix(filename, filepath.Ext(filename))
	name = strings.TrimSpace(name)
	if name == "" || name == "." {
		name = "rosaline-app"
	}
	return filepath.Join(directory, name)
}

func generatedApplicationNeedsSetup(directory string) bool {
	for _, name := range []string{"go.mod", "go.sum", "ui_generated.go"} {
		if _, err := os.Stat(filepath.Join(directory, name)); err != nil {
			return true
		}
	}
	return false
}

func generateProject(project *designProject, directory string) (generationReport, error) {
	var report generationReport
	project.ensureComponentNames()
	if err := project.validate(); err != nil {
		return report, err
	}
	if strings.TrimSpace(directory) == "" {
		return report, fmt.Errorf("choose a project folder first")
	}
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return report, fmt.Errorf("create project folder: %w", err)
	}

	context := makeGenerationContext(project)
	generated := map[string]string{
		"ui_generated.go":     generatedUI(project, context),
		"state_generated.go":  generatedState(project, context),
		"events_generated.go": generatedEvents(project),
	}
	for name, contents := range generated {
		formatted, err := format.Source([]byte(contents))
		if err != nil {
			return report, fmt.Errorf("format %s: %w", name, err)
		}
		path := filepath.Join(directory, name)
		existed, err := replaceGeneratedFile(path, formatted)
		if err != nil {
			return report, fmt.Errorf("write %s: %w", name, err)
		}
		if existed {
			report.Updated = append(report.Updated, name)
		} else {
			report.Created = append(report.Created, name)
		}
	}
	createdAssets, updatedAssets, err := copyProjectAssets(project, directory)
	if err != nil {
		return report, err
	}
	report.Created = append(report.Created, createdAssets...)
	report.Updated = append(report.Updated, updatedAssets...)

	protected := map[string]string{
		"go.mod":      generatedGoMod(project),
		"main.go":     generatedMain(),
		"handlers.go": generatedHandlers(),
		"README.md":   generatedReadme(project),
	}
	for name, contents := range protected {
		path := filepath.Join(directory, name)
		if _, err := os.Stat(path); err == nil {
			report.Kept = append(report.Kept, name)
			continue
		} else if !os.IsNotExist(err) {
			return report, fmt.Errorf("inspect %s: %w", name, err)
		}
		if strings.HasSuffix(name, ".go") {
			formatted, err := format.Source([]byte(contents))
			if err != nil {
				return report, fmt.Errorf("format %s: %w", name, err)
			}
			contents = string(formatted)
		}
		if err := os.WriteFile(path, []byte(contents), 0o644); err != nil {
			return report, fmt.Errorf("write %s: %w", name, err)
		}
		report.Created = append(report.Created, name)
	}

	sort.Strings(report.Created)
	sort.Strings(report.Updated)
	sort.Strings(report.Kept)
	return report, nil
}

func replaceGeneratedFile(path string, contents []byte) (bool, error) {
	existing, err := os.ReadFile(path)
	if err == nil {
		if !strings.Contains(string(existing), generatedMarker) {
			return true, fmt.Errorf("refusing to replace an existing file without the Rosaline Studio generation marker")
		}
		return true, writeFileAtomically(path, contents, 0o644)
	}
	if !os.IsNotExist(err) {
		return false, err
	}
	return false, writeFileAtomically(path, contents, 0o644)
}

func writeFileAtomically(path string, contents []byte, permission os.FileMode) error {
	temporary, err := os.CreateTemp(filepath.Dir(path), ".rosaline-studio-*")
	if err != nil {
		return err
	}
	temporaryPath := temporary.Name()
	defer func() {
		_ = temporary.Close()
		_ = os.Remove(temporaryPath)
	}()
	if err := temporary.Chmod(permission); err != nil {
		return err
	}
	if _, err := temporary.Write(contents); err != nil {
		return err
	}
	if err := temporary.Close(); err != nil {
		return err
	}
	return os.Rename(temporaryPath, path)
}

func makeGenerationContext(project *designProject) *generationContext {
	context := &generationContext{
		fieldsByID:  make(map[string]generatedField),
		widgetsByID: make(map[string]generatedField),
	}
	used := make(map[string]bool)
	var visit func(*designNode)
	visit = func(node *designNode) {
		if node == nil {
			return
		}
		fieldType := stateType(node.Kind)
		if fieldType != "" {
			base := exportedIdentifier(node.Name)
			if base == "" {
				base = exportedIdentifier(string(node.Kind))
			}
			name := uniqueGeneratedName(base, used)
			field := generatedField{Name: name, Type: fieldType}
			context.fieldsByID[node.ID] = field
			context.fields = append(context.fields, field)
		}
		widget := generatedField{Name: node.Component, Type: widgetType(node.Kind)}
		context.widgetsByID[node.ID] = widget
		context.widgets = append(context.widgets, widget)
		for _, child := range node.Children {
			visit(child)
		}
	}
	project.visitRoots(visit)
	return context
}

func widgetType(kind widgetKind) string {
	switch kind {
	case kindColumn, kindRow:
		return "*rosaline.Box"
	case kindGrid:
		return "*rosaline.GridLayout"
	case kindStack:
		return "*rosaline.StackLayout"
	case kindCard:
		return "*rosaline.CardWidget"
	case kindScroll:
		return "*rosaline.ScrollWidget"
	case kindLabel:
		return "*rosaline.LabelWidget"
	case kindImage:
		return "*rosaline.ImageWidget"
	case kindButton:
		return "*rosaline.ButtonWidget"
	case kindTextBox:
		return "*rosaline.TextBoxWidget"
	case kindTextArea:
		return "*rosaline.TextAreaWidget"
	case kindCheckBox:
		return "*rosaline.CheckBoxWidget"
	case kindComboBox:
		return "*rosaline.ComboBoxWidget"
	case kindSlider:
		return "*rosaline.SliderWidget"
	case kindProgressBar:
		return "*rosaline.ProgressBarWidget"
	default:
		return "rosaline.Widget"
	}
}

func stateType(kind widgetKind) string {
	switch kind {
	case kindTextBox, kindTextArea, kindComboBox:
		return "string"
	case kindCheckBox:
		return "bool"
	case kindSlider, kindProgressBar:
		return "float64"
	default:
		return ""
	}
}

func exportedIdentifier(value string) string {
	words := strings.FieldsFunc(value, func(r rune) bool { return !unicode.IsLetter(r) && !unicode.IsDigit(r) })
	var builder strings.Builder
	for _, word := range words {
		if word == "" {
			continue
		}
		runes := []rune(word)
		runes[0] = unicode.ToUpper(runes[0])
		builder.WriteString(string(runes))
	}
	result := builder.String()
	if result == "" || unicode.IsDigit([]rune(result)[0]) {
		return "Value"
	}
	return result
}

func generatedUI(project *designProject, context *generationContext) string {
	imports := fmt.Sprintf("import rosaline %q\n", rosalineModule)
	assetSupport := ""
	if len(projectAssets(project)) != 0 {
		imports = fmt.Sprintf("import (\n\t\"embed\"\n\n\trosaline %q\n)\n", rosalineModule)
		assetSupport = `//go:embed assets/*
var generatedAssets embed.FS

func generatedPicture(name string) *rosaline.Picture {
	picture, err := rosaline.LoadImageFS(generatedAssets, "assets/"+name)
	if err != nil {
		return nil
	}
	return picture
}

`
	}
	main := project.mainForm()
	var setup strings.Builder
	fmt.Fprintf(&setup, "\tgeneratedWidgets = UIWidgets{}\n\tgeneratedWindows = UIWindows{%s: rosaline.MainWindow()}\n", main.Name)
	for _, form := range project.Forms[1:] {
		fmt.Fprintf(&setup, `	generatedWindows.%s = rosaline.NewWindow(rosaline.WindowOptions{
		Title: %q,
		Width: %d,
		Height: %d,
		Padding: %d,
		Theme: theme%s(),
		Parent: generatedWindows.%s,
		Menu: build%sMenu(app),
%s		Content: build%s(app),
	})
`, form.Name, form.Title, max(320, form.Width), max(240, form.Height), max(0, form.Padding), form.Name, main.Name, form.Name, generatedFormCallbacks(form, 2), form.Name)
	}

	var builders strings.Builder
	var themes strings.Builder
	for _, form := range project.Forms {
		fmt.Fprintf(&builders, "func build%s(app *Application) rosaline.Widget {\n\treturn %s\n}\n\n", form.Name, generateNode(form.Root, context, 1))
		builders.WriteString(generateFormMenu(form))
		themes.WriteString(generatedTheme(form.Theme, "theme"+form.Name))
		themes.WriteString("\n\n")
	}

	return fmt.Sprintf(`// %s
package main

%s
%s
func runGeneratedApplication(app *Application) {
%s	rosaline.RunApp(rosaline.App{
		Title: %q,
		Width: %d,
		Height: %d,
		Padding: %d,
		Theme: theme%s(),
		Menu: build%sMenu(app),
%s		Content: build%s(app),
	})
}

%svar generatedWidgets UIWidgets
var generatedWindows UIWindows

// Widgets returns every control created by the visual designer.
func (app *Application) Widgets() *UIWidgets { return &generatedWidgets }

// Windows returns the reusable handle for every designed form.
func (app *Application) Windows() *UIWindows { return &generatedWindows }

func rememberWidget[T rosaline.Widget](slot *T, widget T) T {
	*slot = widget
	return widget
}

%s`, generatedMarker, imports, assetSupport, setup.String(), main.Title, max(320, main.Width), max(240, main.Height), max(0, main.Padding), main.Name, main.Name, generatedFormCallbacks(main, 2), main.Name, builders.String(), themes.String())
}

func generateFormMenu(form *designForm) string {
	var result strings.Builder
	fmt.Fprintf(&result, "func build%sMenu(app *Application) *rosaline.AppMenuBar {\n", form.Name)
	if len(form.Menus) == 0 {
		result.WriteString("\treturn nil\n}\n\n")
		return result.String()
	}
	result.WriteString("\treturn rosaline.MenuBar(\n")
	for _, menu := range form.Menus {
		fmt.Fprintf(&result, "\t\t%s,\n", generateMenuEntry(menu, 2))
	}
	result.WriteString("\t)\n}\n\n")
	return result.String()
}

func generateMenuEntry(menu *designMenu, depth int) string {
	if menu == nil {
		return "rosaline.MenuSeparator()"
	}
	switch menu.Kind {
	case menuKindSeparator:
		return "rosaline.MenuSeparator()"
	case menuKindItem:
		callback := "nil"
		if handler := strings.TrimSpace(menu.Handler); handler != "" {
			callback = "func() { app." + handler + "() }"
		}
		result := fmt.Sprintf("rosaline.MenuItem(%q, %s)", menu.Text, callback)
		if shortcut := strings.TrimSpace(menu.Shortcut); shortcut != "" {
			result += fmt.Sprintf(".Shortcut(%q)", shortcut)
		}
		return result
	case menuKindMenu:
		if len(menu.Children) == 0 {
			return fmt.Sprintf("rosaline.Menu(%q)", menu.Text)
		}
		indent := strings.Repeat("\t", depth)
		childIndent := strings.Repeat("\t", depth+1)
		var result strings.Builder
		fmt.Fprintf(&result, "rosaline.Menu(%q,\n", menu.Text)
		for _, child := range menu.Children {
			fmt.Fprintf(&result, "%s%s,\n", childIndent, generateMenuEntry(child, depth+1))
		}
		result.WriteString(indent + ")")
		return result.String()
	default:
		return "rosaline.MenuSeparator()"
	}
}

func generatedFormCallbacks(form *designForm, depth int) string {
	indent := strings.Repeat("\t", depth)
	var result strings.Builder
	for _, event := range formEventSpecs() {
		handler := formEventHandler(form, event.Name)
		if handler == "" {
			continue
		}
		if event.ReturnsBool {
			fmt.Fprintf(&result, "%s%s: func() bool { return app.%s() },\n", indent, event.Name, handler)
		} else {
			fmt.Fprintf(&result, "%s%s: func() { app.%s() },\n", indent, event.Name, handler)
		}
	}
	return result.String()
}

func generatedState(project *designProject, context *generationContext) string {
	var fields strings.Builder
	for _, field := range context.fields {
		fmt.Fprintf(&fields, "\t%s %s\n", field.Name, field.Type)
	}
	var widgets strings.Builder
	for _, field := range context.widgets {
		fmt.Fprintf(&widgets, "\t%s %s\n", field.Name, field.Type)
	}
	var windows strings.Builder
	for _, form := range project.Forms {
		fmt.Fprintf(&windows, "\t%s *rosaline.Window\n", form.Name)
	}
	return fmt.Sprintf(`// %s
package main

import rosaline %q

// UIState contains values bound to generated Rosaline controls.
type UIState struct {
%s}

// UIWidgets contains direct references to every visually designed component.
type UIWidgets struct {
%s}

// UIWindows contains reusable handles for the primary and secondary forms.
type UIWindows struct {
%s}
`, generatedMarker, rosalineModule, fields.String(), widgets.String(), windows.String())
}

func generatedEvents(project *designProject) string {
	handlers := referencedHandlers(project)
	if len(handlers) == 0 {
		return fmt.Sprintf("// %s\npackage main\n", generatedMarker)
	}
	var methods strings.Builder
	for _, name := range handlers {
		body := strings.TrimSpace(project.Handlers[name])
		if body == "" {
			if handlerReturnsBool(project, name) {
				body = "// Allow the close request by default.\nreturn true"
			} else {
				body = "// Add your event code in Rosaline Studio."
			}
		}
		result := ""
		if handlerReturnsBool(project, name) {
			result = " bool"
		}
		fmt.Fprintf(&methods, "func (app *Application) %s()%s {\n%s\n}\n\n", name, result, indentBody(body, "\t"))
	}
	return fmt.Sprintf(`// %s
package main

import rosaline %q

var _ = rosaline.Message

%s`, generatedMarker, rosalineModule, methods.String())
}

func referencedHandlers(project *designProject) []string {
	seen := make(map[string]bool)
	var visit func(*designNode)
	visit = func(node *designNode) {
		if node == nil {
			return
		}
		for _, handler := range node.Events {
			if handler = strings.TrimSpace(handler); handler != "" {
				seen[handler] = true
			}
		}
		for _, child := range node.Children {
			visit(child)
		}
	}
	if project != nil {
		for _, form := range project.Forms {
			if form == nil {
				continue
			}
			for _, handler := range form.Events {
				if handler = strings.TrimSpace(handler); handler != "" {
					seen[handler] = true
				}
			}
			visitDesignMenus(form.Menus, func(menu *designMenu) {
				if handler := strings.TrimSpace(menu.Handler); handler != "" {
					seen[handler] = true
				}
			})
			visit(form.Root)
		}
	}
	result := make([]string, 0, len(seen))
	for name := range seen {
		result = append(result, name)
	}
	sort.Strings(result)
	return result
}

func indentBody(body, prefix string) string {
	lines := strings.Split(body, "\n")
	for index, line := range lines {
		if strings.TrimSpace(line) != "" {
			lines[index] = prefix + line
		}
	}
	return strings.Join(lines, "\n")
}

func generatedMain() string {
	return `package main

func main() {
	runGeneratedApplication(&Application{})
}
`
}

func generatedHandlers() string {
	return `package main

// Application contains your program's state and behavior. Rosaline Studio
// never overwrites this file.
type Application struct {
	State UIState
}

// Add reusable application methods and non-visual logic below. Visual event
// methods are edited in Studio and generated into events_generated.go.
`
}

func generatedGoMod(project *designProject) string {
	return fmt.Sprintf("module %s\n\ngo 1.25.0\n\nrequire %s %s\n", strings.TrimSpace(project.Module), rosalineModule, rosalineVersion)
}

func generatedReadme(project *designProject) string {
	title := "Rosaline Application"
	if main := project.mainForm(); main != nil {
		title = main.Title
	}
	return fmt.Sprintf(`# %s

This application was visually designed with Rosaline Studio.

Run it with:

~~~bash
CGO_ENABLED=0 go run .
~~~

Edit visual event handlers in Rosaline Studio. Put reusable application logic
in handlers.go. Studio regenerates ui_generated.go, state_generated.go, and
events_generated.go, so do not edit those three files directly. Event code can
open designed forms through app.Windows() and update controls through
app.Widgets().
`, title)
}

func generatedTheme(name, functionName string) string {
	switch name {
	case "Midnight":
		return `func ` + functionName + `() rosaline.Theme {
	theme := rosaline.DefaultTheme
	theme.Background = rosaline.Hex("#140d1d")
	theme.Surface = rosaline.Hex("#24152e")
	theme.Primary = rosaline.Hex("#ff79b7")
	theme.Text = rosaline.Hex("#fff0fa")
	theme.Muted = rosaline.Hex("#c39ab4")
	theme.Border = rosaline.Hex("#73445f")
	return theme
}`
	case "Lavender":
		return `func ` + functionName + `() rosaline.Theme {
	theme := rosaline.DefaultTheme
	theme.Background = rosaline.Hex("#f7f1ff")
	theme.Surface = rosaline.Hex("#ffffff")
	theme.Primary = rosaline.Hex("#8554bd")
	theme.Text = rosaline.Hex("#2d2038")
	theme.Muted = rosaline.Hex("#74627f")
	theme.Border = rosaline.Hex("#d7c3e9")
	return theme
}`
	default:
		return `func ` + functionName + `() rosaline.Theme { return rosaline.DefaultTheme }`
	}
}

func generateNode(node *designNode, context *generationContext, depth int) string {
	if node == nil {
		return "rosaline.Spacer(0, 0)"
	}
	indent := strings.Repeat("\t", depth)
	childIndent := strings.Repeat("\t", depth+1)
	children := func() string {
		if len(node.Children) == 0 {
			return ""
		}
		parts := make([]string, 0, len(node.Children))
		for _, child := range node.Children {
			parts = append(parts, childIndent+generateNode(child, context, depth+1))
		}
		return "\n" + strings.Join(parts, ",\n") + ",\n" + indent
	}
	oneChild := func() string {
		if len(node.Children) == 0 {
			return "rosaline.Spacer(0, 0)"
		}
		return generateNode(node.Children[0], context, depth+1)
	}

	var expression string
	switch node.Kind {
	case kindColumn:
		expression = "rosaline.Column(" + children() + ")" + layoutModifiers(node)
	case kindRow:
		expression = "rosaline.Row(" + children() + ")" + layoutModifiers(node)
	case kindGrid:
		childList := children()
		if childList == "" {
			expression = fmt.Sprintf("rosaline.Grid(%d)", max(1, node.Columns))
		} else {
			expression = fmt.Sprintf("rosaline.Grid(%d,%s)", max(1, node.Columns), childList)
		}
		expression += layoutModifiers(node)
	case kindStack:
		expression = "rosaline.Stack(" + children() + ")"
		if node.Expand {
			expression += ".Expand()"
		}
	case kindCard:
		expression = fmt.Sprintf("rosaline.Card(%s).Padding(%d)", oneChild(), max(0, node.Padding))
		if node.Expand {
			expression += ".Expand()"
		}
	case kindScroll:
		expression = "rosaline.Scroll(" + oneChild() + ")"
		if node.Width > 0 && node.Height > 0 {
			expression += fmt.Sprintf(".Size(%d, %d)", node.Width, node.Height)
		}
		if node.Expand {
			expression += ".Expand()"
		}
	case kindLabel:
		expression = fmt.Sprintf("rosaline.Label(%q)", node.Text)
		if node.Bold {
			expression += ".Bold()"
		}
	case kindImage:
		picture := "nil"
		if node.Asset != "" {
			picture = fmt.Sprintf("generatedPicture(%q)", node.Asset)
		}
		expression = fmt.Sprintf("rosaline.Image(%s).Placeholder(%q)", picture, defaultText(node.Text, "Choose an image"))
		if node.Width > 0 && node.Height > 0 {
			expression += fmt.Sprintf(".Fit(%d, %d)", node.Width, node.Height)
		}
		expression += generatedEventModifier(node, eventClick, "")
		if node.Expand {
			expression += ".Expand()"
		}
	case kindButton:
		if handler := eventHandler(node, eventClick); handler != "" {
			expression = fmt.Sprintf("rosaline.Button(%q, func() { app.%s() })", node.Text, handler)
		} else {
			expression = fmt.Sprintf("rosaline.Button(%q, nil)", node.Text)
		}
		if node.Primary {
			expression += ".Primary()"
		}
	case kindTextBox:
		field := context.fieldsByID[node.ID]
		expression = fmt.Sprintf("rosaline.TextBox(&app.State.%s)", field.Name)
		if node.Text != "" {
			expression += fmt.Sprintf(".Placeholder(%q)", node.Text)
		}
		if node.Password {
			expression += ".Password()"
		}
		expression += generatedEventModifier(node, eventChange, "string")
		expression += generatedEventModifier(node, eventSubmit, "string")
	case kindTextArea:
		field := context.fieldsByID[node.ID]
		expression = fmt.Sprintf("rosaline.TextArea(&app.State.%s)", field.Name)
		if node.Expand {
			expression += ".Expand()"
		}
		expression += generatedEventModifier(node, eventChange, "string")
	case kindCheckBox:
		field := context.fieldsByID[node.ID]
		expression = fmt.Sprintf("rosaline.CheckBox(%q, &app.State.%s)", node.Text, field.Name)
		expression += generatedEventModifier(node, eventChange, "bool")
	case kindComboBox:
		field := context.fieldsByID[node.ID]
		options := make([]string, 0, len(node.Options))
		for _, option := range node.Options {
			options = append(options, strconv.Quote(option))
		}
		expression = fmt.Sprintf("rosaline.ComboBox(&app.State.%s", field.Name)
		if len(options) != 0 {
			expression += ", " + strings.Join(options, ", ")
		}
		expression += ")"
		expression += generatedEventModifier(node, eventChange, "string")
	case kindSlider:
		field := context.fieldsByID[node.ID]
		minimum, maximum := node.Minimum, node.Maximum
		if maximum <= minimum {
			maximum = minimum + 100
		}
		expression = fmt.Sprintf("rosaline.Slider(&app.State.%s, %s, %s)", field.Name, numberLiteral(minimum), numberLiteral(maximum))
		if node.Step > 0 {
			expression += fmt.Sprintf(".Step(%s)", numberLiteral(node.Step))
		}
		if node.Vertical {
			expression += ".Vertical()"
		}
		expression += generatedEventModifier(node, eventChange, "float64")
	case kindProgressBar:
		field := context.fieldsByID[node.ID]
		expression = fmt.Sprintf("rosaline.ProgressBar(&app.State.%s)", field.Name)
		if node.Maximum > 0 && node.Maximum != 100 {
			expression += fmt.Sprintf(".Maximum(%s)", numberLiteral(node.Maximum))
		}
		if node.Vertical {
			expression += ".Vertical()"
		}
	case kindSpacer:
		expression = fmt.Sprintf("rosaline.Spacer(%d, %d)", max(0, node.Width), max(0, node.Height))
	default:
		expression = "rosaline.Label(\"Unknown widget\")"
	}

	if node.Kind != kindScroll && node.Kind != kindSpacer && node.Kind != kindImage && node.Width > 0 && node.Height > 0 {
		size := fmt.Sprintf("rosaline.Size(%%s, %d, %d)", node.Width, node.Height)
		field := context.widgetsByID[node.ID]
		expression = fmt.Sprintf(size, fmt.Sprintf("rememberWidget(&generatedWidgets.%s, %s)", field.Name, expression))
		return expression
	}
	field := context.widgetsByID[node.ID]
	expression = fmt.Sprintf("rememberWidget(&generatedWidgets.%s, %s)", field.Name, expression)
	return expression
}

func generatedEventModifier(node *designNode, event, valueType string) string {
	handler := eventHandler(node, event)
	if handler == "" {
		return ""
	}
	parameter := ""
	if valueType != "" {
		parameter = valueType
	}
	return fmt.Sprintf(".%s(func(%s) { app.%s() })", event, parameter, handler)
}

func layoutModifiers(node *designNode) string {
	result := fmt.Sprintf(".Gap(%d).Padding(%d)", max(0, node.Gap), max(0, node.Padding))
	if node.Expand {
		result += ".Expand()"
	}
	return result
}

func numberLiteral(value float64) string {
	return strconv.FormatFloat(value, 'f', -1, 64)
}
